# Generated by Django 3.2.13 on 2023-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='book_files/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
